import { useRef, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { UploadCloud, FileText, CheckCircle2, AlertCircle, Clock } from 'lucide-react';
import { useGetOwnApplication, useGetOwnAdvisor, useResubmitAdvisorApplication, useUploadAdvisorDocument } from '../../../integrations/backend/hooks/useAdvisors';
import { getOwnDocumentUrl, type DocumentoAsesor } from '../../../integrations/backend/advisors.service';
import { operationError } from '../../../integrations/backend/versioning';
import { Button } from '../../atoms/Button';
import { Skeleton } from '../../atoms/Skeleton';

const types = [
  { code: 'IDENTIFICACION_OFICIAL', label: 'Identificación oficial (INE / Pasaporte)' },
  { code: 'CONSTANCIA_ACTIVIDAD_INMOBILIARIA', label: 'Constancia de actividad inmobiliaria' },
  { code: 'CONSTANCIA_SITUACION_FISCAL', label: 'Constancia de situación fiscal' },
  { code: 'LICENCIA_INMOBILIARIA', label: 'Licencia inmobiliaria (opcional)' },
] as const;
type DocumentCode = typeof types[number]['code'];
function DocumentCard({ label, current, pending, enabled, onUpload }: { label: string; current?: DocumentoAsesor; pending: boolean; enabled: boolean; onUpload: (file: File) => void }) {
  const input = useRef<HTMLInputElement>(null), url = useMutation({ mutationFn: () => getOwnDocumentUrl(current!.id) });
  const status = !current ? 'Faltante' : current.estado === 'VERIFICADO' ? 'Verificado' : current.estado === 'RECHAZADO' ? 'Rechazado' : 'Pendiente de revisión';
  const icon = current?.estado === 'VERIFICADO' ? <CheckCircle2 className="w-5 h-5 text-green-500" /> : current?.estado === 'PENDIENTE' ? <Clock className="w-5 h-5 text-yellow-500" /> : <AlertCircle className="w-5 h-5 text-red-400" />;
  return <div className="flex flex-col gap-3 h-full"><div className="relative flex-1 min-h-[220px] rounded-3xl border-2 border-dashed flex flex-col items-center justify-center p-6 text-center transition-all overflow-hidden group border-gray-200 dark:border-inmo-darktertiary hover:border-inmo-accent hover:bg-inmo-accent/5 dark:hover:bg-inmo-accent/10" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if (enabled && !pending && event.dataTransfer.files[0]) onUpload(event.dataTransfer.files[0]); }}><div className="absolute top-4 right-4 z-10" title={status}>{icon}</div><div className="flex flex-col items-center gap-3 w-full"><div className="w-14 h-14 rounded-full bg-transparent flex items-center justify-center text-gray-400 group-hover:text-inmo-accent group-hover:scale-110 transition-all">{current ? <FileText className="w-6 h-6" /> : <UploadCloud className="w-6 h-6" />}</div>{current && <p className="text-sm font-bold text-gray-500 dark:text-gray-400 break-all">{current.nombre}</p>}<p className="text-xs text-gray-400">{status}{current ? ` · ${(current.tamano_bytes / 1024).toFixed(0)} KB` : ''}</p>
    {enabled && <><input ref={input} type="file" className="sr-only" aria-label={'Subir ' + label} accept="application/pdf,image/jpeg,image/webp" disabled={pending} onChange={event => { const file = event.currentTarget.files?.[0]; if (file) onUpload(file); event.currentTarget.value = ''; }} /><button type="button" className="text-sm font-bold text-gray-500 dark:text-gray-400 group-hover:text-inmo-accent disabled:opacity-50" disabled={pending} onClick={() => input.current?.click()}>{pending ? 'Subiendo y comprobando…' : current ? 'Adjuntar versión actualizada' : 'Subir archivo'}</button></>}
    <span className="text-xs text-gray-400">PDF, JPEG o WebP · hasta 5 MB</span>{current && <Button variant="text" className="!text-xs" isLoading={url.isPending} onClick={() => url.mutate()}>Consultar archivo privado</Button>}{url.data && <a href={url.data.url} target="_blank" rel="noopener noreferrer" className="text-xs text-inmo-accent underline">Abrir archivo · enlace temporal</a>}{url.isError && <p role="alert" className="text-xs text-inmo-danger">{operationError(url.error)}</p>}
  </div></div><span className="font-bold text-sm text-center text-inmo-secondary dark:text-white px-2 leading-tight">{label}</span></div>;
}
export function AdvisorValidationView({ embedded = false }: { embedded?: boolean }) {
  const advisor = useGetOwnAdvisor(), application = useGetOwnApplication(), upload = useUploadAdvisorDocument(), resubmit = useResubmitAdvisorApplication();
  const [notice, setNotice] = useState(''), [uploading, setUploading] = useState<string | null>(null), current = application.data?.value;
  const send = async (type: DocumentCode, file: File) => { setNotice(''); setUploading(type); try { await upload.mutateAsync({ tipo: type, file }); setNotice('Documento recibido y confirmado. Se conserva la evidencia anterior.'); } catch { /* error below */ } finally { setUploading(null); } };
  return <main className={(embedded ? 'px-6 mt-8 pb-8 ' : 'max-w-5xl mx-auto px-4 md:px-6 pt-28 pb-32 ') + 'flex flex-col gap-6 animate-in fade-in zoom-in-95 duration-300 text-inmo-secondary dark:text-white font-inter'}><div><h1 className="font-montserrat font-bold text-xl mb-2">Expediente</h1><p className="text-gray-500 dark:text-gray-400 text-sm">Arrastra o selecciona tus documentos oficiales. Los archivos son privados y se revisan para autorizar tu perfil profesional.</p></div>
    {advisor.isPending || application.isPending ? <Skeleton className="h-64" /> : advisor.isError || application.isError ? <div role="alert" className="space-y-3"><p>{operationError(advisor.error ?? application.error)}</p><Button variant="secondary" onClick={() => { void advisor.refetch(); void application.refetch(); }}>Reintentar consulta</Button></div> : current && <><div className="flex flex-wrap gap-3 justify-between items-center"><p className="text-sm font-bold">{advisor.data?.nombre_comercial} · Solicitud #{current.id}</p><span className={`px-3 py-1.5 rounded-full text-xs font-bold ${current.estado === 'APROBADA' ? 'bg-inmo-success/10 text-inmo-success' : current.estado === 'RECHAZADA' ? 'bg-inmo-danger/10 text-inmo-danger' : 'bg-inmo-warning/10 text-inmo-warning'}`}>{current.estado}</span></div>{current.motivo && <div className="rounded-2xl p-4 bg-gray-50 dark:bg-inmo-darkcard"><p className="font-bold text-sm">Motivo de decisión</p><p className="text-sm text-gray-500 mt-2 whitespace-pre-wrap">{current.motivo}</p></div>}
      {current.estado === 'RECHAZADA' && <Button variant="secondary" isLoading={resubmit.isPending} onClick={async () => { try { await resubmit.mutateAsync(); setNotice('Nueva solicitud creada. Los expedientes anteriores se conservan.'); } catch { /* error below */ } }}>Abrir nueva solicitud</Button>}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 flex-1 min-h-[400px]">{types.filter(type => type.code === 'LICENCIA_INMOBILIARIA' || (current.tipos_requeridos ?? ['IDENTIFICACION_OFICIAL', 'CONSTANCIA_ACTIVIDAD_INMOBILIARIA']).includes(type.code)).map(type => <DocumentCard key={type.code + current.id} label={type.label} current={current.documentos.filter(document => document.tipo === type.code).at(-1)} pending={upload.isPending} enabled={current.estado === 'PENDIENTE'} onUpload={file => void send(type.code, file)} />)}</div><p className="text-xs text-gray-500">Identificación y constancia fiscal son obligatorias para solicitudes nuevas. La licencia es opcional. Los expedientes anteriores conservan sus requisitos originales.</p>
      {current.documentos.length > 0 && <details className="rounded-2xl bg-gray-50 dark:bg-inmo-darkcard p-4"><summary className="cursor-pointer text-sm font-bold">Documentos recibidos ({current.documentos.length})</summary><ul className="mt-3 space-y-2 text-sm text-gray-500">{current.documentos.map(document => <li key={document.id}>{document.nombre} · {document.estado}</li>)}</ul></details>}
    </>}{notice && <p role="status" className="text-sm text-inmo-success">{notice}</p>}{uploading && <p role="status" className="text-xs text-gray-500">Comprobando la carga del documento…</p>}{(upload.isError || resubmit.isError) && <p role="alert" className="text-sm text-inmo-danger">{operationError(upload.error ?? resubmit.error)}</p>}
  </main>;
}
