import { useState } from 'react';
import { useInfiniteQuery, useMutation } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { Download, SlidersHorizontal, MoreVertical, User, Home, MessageSquare } from 'lucide-react';
import { Button } from '../../atoms/Button';
import { IconButton } from '../../atoms/IconButton';
import { Select } from '../../atoms/Select';
import { Textarea } from '../../atoms/Textarea';
import { SearchBar } from '../../molecules/SearchBar';
import { ConfirmModal } from '../../molecules/ConfirmModal';
import { SplitViewLayout } from '../../templates/SplitViewLayout';
import { getAdminReports } from '../../../integrations/backend/administration.service';
import { useGetAdminReport, useResolveAdminReport } from '../../../integrations/backend/hooks/useAdministration';
import { downloadCSV } from '../../../integrations/backend/operations.service';
import { operationError } from '../../../integrations/backend/versioning';

type Action = 'DESCARTAR' | 'PAUSAR_PROPIEDAD' | 'DESACTIVAR_CUENTA' | 'OCULTAR_MENSAJE';
const labels: Record<string, string> = { CUENTA: 'Usuario', PROPIEDAD: 'Propiedad', MENSAJE: 'Mensaje', DESCARTAR: 'Descartar reporte', PAUSAR_PROPIEDAD: 'Pausar propiedad', DESACTIVAR_CUENTA: 'Desactivar cuenta', OCULTAR_MENSAJE: 'Ocultar mensaje' };
const date = (value: string | null) => value ? new Date(value).toLocaleString('es-MX', { timeZone: 'America/Mexico_City' }) : '—';
function TargetIcon({ type }: { type: string }) { return type === 'CUENTA' ? <User className="w-4 h-4 md:w-5 md:h-5" /> : type === 'PROPIEDAD' ? <Home className="w-4 h-4 md:w-5 md:h-5" /> : <MessageSquare className="w-4 h-4 md:w-5 md:h-5" />; }
export function AdminReportsView() {
  const [params, setParams] = useSearchParams(), id = params.get('report') ?? '';
  const [searchQuery, setSearchQuery] = useState(''), [showFilters, setShowFilters] = useState(false), [filterType, setFilterType] = useState(''), [filterStatus, setFilterStatus] = useState(''), [reason, setReason] = useState(''), [action, setAction] = useState<Action | null>(null);
  const filters = { texto: searchQuery, estado: filterStatus || undefined, tipo: filterType || undefined };
  const list = useInfiniteQuery({ queryKey: ['admin', 'reports', filters], queryFn: ({ pageParam }) => getAdminReports({ limit: 20, cursor: pageParam, ...filters }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor ?? undefined });
  const detail = useGetAdminReport(id), resolve = useResolveAdminReport(), exporting = useMutation({ mutationFn: () => downloadCSV('reportes', filters) }), report = detail.data;
  const select = (id: string) => { setParams(id ? { report: id } : {}); setReason(''); setAction(null); resolve.reset(); };
  const confirm = async () => { if (!report || !action || !reason.trim()) throw new Error('Escribe el motivo de resolución.'); await resolve.mutateAsync({ id, accion: action, motivo: reason.trim() }); setReason(''); };
  const reports = list.data?.pages.flatMap(page => page.items) ?? [];
  const main = <div className="flex flex-col gap-4 md:gap-6 h-full w-full pt-[100px] pb-[100px] px-4 md:px-6 animate-in fade-in">
    <header className="flex justify-between items-center shrink-0"><div><h1 className="font-montserrat font-bold text-2xl text-inmo-secondary dark:text-white">Reportes y Auditoría</h1><p className="font-inter text-sm text-gray-500 dark:text-gray-400">Revisión humana y resoluciones auditadas</p></div><Button variant="secondary" icon={<Download className="w-4 h-4" />} className="hidden md:flex px-6" isLoading={exporting.isPending} onClick={() => exporting.mutate()}>Exportar CSV</Button><IconButton variant="secondary" icon={<Download className="w-5 h-5" />} className="md:hidden" aria-label="Exportar reportes CSV" disabled={exporting.isPending} onClick={() => exporting.mutate()} /></header>
    <div className="flex flex-col gap-3 shrink-0"><div className="flex gap-3 items-center"><div className="flex-1"><SearchBar value={searchQuery} onChange={setSearchQuery} size="slim" placeholder="Buscar en los motivos de reportes..." /></div><IconButton onClick={() => setShowFilters(!showFilters)} aria-label="Filtros de reportes" aria-expanded={showFilters} className={`w-[44px] h-[44px] md:w-[50px] md:h-[50px] rounded-xl border transition-all flex items-center justify-center shrink-0 ${showFilters ? 'bg-inmo-accent text-white border-inmo-accent shadow-glow' : 'bg-white dark:bg-inmo-darkcard text-gray-500 border-gray-200 dark:border-inmo-darktertiary shadow-soft hover:bg-gray-50 dark:hover:bg-inmo-darkbg'}`} icon={<SlidersHorizontal className="w-5 h-5" />} /></div>
      {showFilters && <div className="grid grid-cols-1 md:grid-cols-2 gap-3 p-4 bg-gray-50 dark:bg-inmo-darkcard rounded-atom border border-gray-100 dark:border-inmo-darktertiary animate-in slide-in-from-top-2 fade-in"><Select aria-label="Tipo de reporte" value={filterType} onChange={event => setFilterType(event.target.value)} wrapperClassName="!h-[56px] !rounded-xl !shadow-none !border !border-gray-200 dark:!border-gray-700" className="!text-sm"><option value="">Cualquier tipo</option>{['CUENTA', 'PROPIEDAD', 'MENSAJE'].map(type => <option key={type} value={type}>{labels[type]}</option>)}</Select><Select aria-label="Estado de reporte" value={filterStatus} onChange={event => setFilterStatus(event.target.value)} wrapperClassName="!h-[56px] !rounded-xl !shadow-none !border !border-gray-200 dark:!border-gray-700" className="!text-sm"><option value="">Cualquier estado</option>{['PENDIENTE', 'EN_REVISION', 'CERRADO'].map(state => <option key={state}>{state}</option>)}</Select></div>}
    </div>
    {(list.isError || exporting.isError) && <p role="alert" className="font-inter text-sm">{operationError(list.error ?? exporting.error)} <button className="text-inmo-accent" onClick={() => void list.refetch()}>Reintentar consulta</button></p>}
    <div className="flex-auto min-h-0 overflow-y-auto pb-10 custom-scrollbar"><div className="hidden md:grid grid-cols-12 gap-4 px-6 py-3 mb-2 font-inter font-semibold text-xs text-gray-500 uppercase tracking-wider"><div className="col-span-4">Elemento</div><div className="col-span-3">Tipo / Categoría</div><div className="col-span-2">Estado</div><div className="col-span-2">Última actividad</div><div className="col-span-1 text-center">Acciones</div></div><div className="flex flex-col gap-3">{reports.map(report => <div key={report.id} className="bg-white dark:bg-inmo-darkcard p-4 md:px-6 md:py-4 rounded-atom md:rounded-2xl shadow-soft border border-gray-100 dark:border-inmo-darktertiary flex flex-col md:grid md:grid-cols-12 md:items-center gap-3 md:gap-4 transition-all hover:border-gray-200 dark:hover:border-gray-700"><div className="md:col-span-4 flex items-center gap-3"><div className="p-2.5 rounded-full bg-gray-50 dark:bg-inmo-darkbg text-gray-500 shrink-0"><TargetIcon type={report.tipo_objetivo} /></div><button onClick={() => select(report.id)} className="flex flex-col min-w-0 text-left"><span className="font-inter font-bold text-sm md:text-base text-inmo-secondary dark:text-white truncate">Reporte #{report.id} · {labels[report.tipo_objetivo]} #{report.objetivo_id}</span><span className="md:hidden font-inter text-xs text-gray-500 truncate mt-0.5">{report.categoria}</span></button><IconButton className="md:hidden ml-auto p-2 text-gray-400 !w-auto !h-auto !bg-transparent !border-none" icon={<MoreVertical className="w-5 h-5" />} aria-label={'Revisar reporte ' + report.id} onClick={() => select(report.id)} /></div><div className="hidden md:flex md:col-span-3 flex-col"><span className="font-inter text-sm font-semibold text-inmo-secondary dark:text-white">{labels[report.tipo_objetivo]}</span><span className="font-inter text-xs text-gray-500">{report.categoria}</span></div><div className="md:col-span-2 flex items-center"><span className={`px-2.5 py-1 rounded-full border text-caption md:text-xs font-bold font-inter ${report.estado === 'CERRADO' ? 'bg-inmo-success/10 text-inmo-success border-inmo-success/20' : 'bg-inmo-warning/10 text-inmo-warning border-inmo-warning/20'}`}>{report.estado}</span></div><div className="hidden md:flex md:col-span-2 items-center"><span className="font-inter text-sm text-gray-500">{date(report.resuelto_at ?? report.registrado_at)}</span></div><div className="hidden md:flex md:col-span-1 justify-center items-center"><IconButton className="p-2 text-gray-400 rounded-full !w-auto !h-auto !bg-transparent !border-none" icon={<MoreVertical className="w-5 h-5" />} aria-label={'Revisar reporte ' + report.id} onClick={() => select(report.id)} /></div></div>)}
      {!reports.length && <p className="p-8 text-center font-inter text-gray-500">{list.isPending ? 'Cargando reportes…' : list.isError ? 'La consulta no está disponible.' : 'No hay reportes en esta vista.'}</p>}{list.hasNextPage && <Button variant="secondary" isLoading={list.isFetchingNextPage} onClick={() => void list.fetchNextPage()}>Cargar más reportes</Button>}
    </div></div>
  </div>;
  const side = <div className="p-6 space-y-5 font-inter h-full overflow-y-auto overscroll-contain custom-scrollbar">{detail.isPending ? <p>Cargando reporte…</p> : detail.isError ? <p role="alert">{operationError(detail.error)}</p> : report && <><h2 className="font-montserrat text-xl font-bold text-inmo-secondary dark:text-white">Reporte #{id}</h2><p className="text-sm text-gray-500">{labels[report.tipo_objetivo]} #{report.objetivo_id} · {report.categoria} · {report.estado}</p><p className="text-xs text-gray-500">Registrado: {date(report.registrado_at)}</p><section className="rounded-2xl bg-gray-50 dark:bg-inmo-darkbg p-4"><h3 className="font-bold text-sm">Motivo del reporte</h3><p className="whitespace-pre-wrap break-words mt-3 text-sm">{report.motivo}</p></section>{report.tipo_objetivo === 'PROPIEDAD' && <Link className="text-inmo-accent underline text-sm" to={'/admin/publicaciones?property=' + report.objetivo_id}>Revisar propiedad</Link>}{report.tipo_objetivo === 'CUENTA' && <Link className="text-inmo-accent underline text-sm" to={'/admin/asesores?cuenta=' + report.objetivo_id}>Revisar cuenta</Link>}{report.resolucion && <p className="text-sm">Resolución: {report.resolucion} · {date(report.resuelto_at)}</p>}
      {report.estado !== 'CERRADO' && <section className="space-y-4"><Textarea aria-label="Motivo de resolución" value={reason} onChange={event => setReason(event.target.value)} placeholder="Motivo obligatorio de la decisión" maxLength={1000} /><div className="flex flex-wrap gap-3">{(['DESCARTAR', report.tipo_objetivo === 'PROPIEDAD' ? 'PAUSAR_PROPIEDAD' : report.tipo_objetivo === 'CUENTA' ? 'DESACTIVAR_CUENTA' : 'OCULTAR_MENSAJE'] as Action[]).map(action => <Button key={action} variant="secondary" disabled={!reason.trim() || resolve.isPending} onClick={() => setAction(action)}>{labels[action]}</Button>)}</div></section>}{resolve.isError && <p role="alert">{operationError(resolve.error)} <button className="text-inmo-accent" onClick={() => void detail.refetch()}>Consultar estado vigente</button></p>}{resolve.isSuccess && <p role="status" className="text-inmo-success text-sm">Resolución aplicada y auditada.</p>}
    </>}</div>;
  return <><SplitViewLayout mainContent={main} sideContent={side} isOpen={!!id} onClose={() => select('')} sideTitle="Revisión del reporte" /><ConfirmModal isOpen={!!action} onClose={() => setAction(null)} onConfirm={confirm} title={labels[action ?? 'DESCARTAR']} message="La decisión se aplicará al objetivo reportado y quedará auditada con el motivo indicado. Se conservará el historial." confirmVariant={action === 'DESCARTAR' ? 'accent' : 'warning'} /></>;
}
