import { useState } from 'react';
import { useInfiniteQuery, useMutation } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { CreditCard, Download, Eye } from 'lucide-react';
import { ModuleLayout } from '../../templates/ModuleLayout';
import { SplitViewLayout } from '../../templates/SplitViewLayout';
import { SearchBar } from '../../molecules/SearchBar';
import { PeriodDropdown } from '../../molecules/PeriodDropdown';
import { Button } from '../../atoms/Button';
import { IconButton } from '../../atoms/IconButton';
import { Select } from '../../atoms/Select';
import { getPayments, type PagoReal } from '../../../integrations/backend/engagement.service';
import { getAdminSubscriptions } from '../../../integrations/backend/administration.service';
import { useStatistics } from '../../../integrations/backend/hooks/useEngagement';
import { downloadCSV } from '../../../integrations/backend/operations.service';
import { operationError } from '../../../integrations/backend/versioning';

const date = (value: string | null) => value ? new Date(value).toLocaleString('es-MX', { timeZone: 'America/Mexico_City' }) : '—';
const money = (value: string) => Number(value).toLocaleString('es-MX', { style: 'currency', currency: 'MXN' });
const statuses = ['PENDIENTE', 'CONFIRMADO', 'FALLIDO', 'EXPIRADO'];
const row = 'bg-white dark:bg-inmo-darkcard p-4 md:px-6 md:py-4 rounded-atom md:rounded-2xl shadow-soft border border-gray-100 dark:border-inmo-darktertiary flex flex-col md:grid md:grid-cols-12 md:items-center gap-3 md:gap-4 transition-all hover:border-gray-200 dark:hover:border-gray-700';

export function AdminFinanceView() {
  const [tab, setTab] = useState<'pagos' | 'suscripciones'>('pagos'), [text, setText] = useState(''), [state, setState] = useState(''), [days, setDays] = useState('30 días'), [selected, setSelected] = useState<PagoReal | null>(null);
  const statistics = useStatistics(true, Number.parseInt(days)), payments = useInfiniteQuery({ queryKey: ['admin', 'payments', text, state], queryFn: ({ pageParam }) => getPayments(true, pageParam, { texto: text, estado: state || undefined }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor ?? undefined });
  const subscriptions = useInfiniteQuery({ queryKey: ['admin', 'subscriptions'], queryFn: ({ pageParam }) => getAdminSubscriptions({ limit: 20, cursor: pageParam }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor ?? undefined, enabled: tab === 'suscripciones' });
  const exporting = useMutation({ mutationFn: () => downloadCSV(tab, tab === 'pagos' ? { texto: text, estado: state || undefined } : {}) });
  const list = tab === 'pagos' ? payments : subscriptions;
  const main = <ModuleLayout title="Finanzas" subtitle="Pagos confirmados por el proveedor y periodos reales de suscripción." isFullScreen noScroll showSearch={false} showFilters={false} headerEndContent={<PeriodDropdown selectedPeriod={days} onChange={setDays} options={['7 días', '30 días', '90 días', '365 días']} />}>
    <div className="flex flex-col gap-4 md:gap-6 h-full min-h-0 w-full font-inter">
      <div className="grid grid-cols-2 gap-4 shrink-0">{[{ label: `Ingresos confirmados · ${days}`, value: statistics.data ? money(statistics.data.ingresos_confirmados_mxn) : '—' }, { label: 'Suscripciones con periodo vigente', value: statistics.data ? Object.values(statistics.data.suscripciones_por_plan ?? {}).reduce((total, count) => total + count, 0) : '—' }].map(metric => <div key={metric.label} className="bg-white dark:bg-inmo-darkcard p-4 rounded-card border border-gray-100 dark:border-inmo-darktertiary shadow-soft text-center"><p className="font-montserrat font-black text-2xl text-inmo-secondary dark:text-white">{metric.value}</p><p className="text-[10px] uppercase tracking-widest font-bold text-gray-500 mt-1">{metric.label}</p></div>)}</div>
      {statistics.isError && <p role="alert">{operationError(statistics.error)} <button className="text-inmo-accent" onClick={() => void statistics.refetch()}>Reintentar</button></p>}
      <div className="flex flex-wrap justify-between gap-3 shrink-0"><nav aria-label="Registros financieros" className="flex gap-2">{(['pagos', 'suscripciones'] as const).map(value => <Button key={value} variant={tab === value ? 'accent' : 'secondary'} onClick={() => { setTab(value); setSelected(null); exporting.reset(); }}>{value === 'pagos' ? 'Pagos' : 'Suscripciones'}</Button>)}</nav><Button variant="secondary" icon={<Download className="w-4 h-4" />} isLoading={exporting.isPending} onClick={() => exporting.mutate()}>Exportar CSV</Button></div>
      {tab === 'pagos' && <div className="flex flex-col md:flex-row gap-3 shrink-0"><SearchBar size="slim" placeholder="Buscar por nombre del asesor..." value={text} onChange={setText} className="flex-1" /><Select aria-label="Estado del pago" value={state} onChange={event => setState(event.target.value)}><option value="">Todos los estados</option>{statuses.map(value => <option key={value}>{value}</option>)}</Select></div>}
      {(list.isError || exporting.isError) && <p role="alert">{operationError(list.error ?? exporting.error)} <button className="text-inmo-accent" onClick={() => void list.refetch()}>Reintentar consulta</button></p>}
      <div className="flex-auto min-h-0 overflow-y-auto custom-scrollbar pb-24 space-y-3">
        <div className="hidden md:grid grid-cols-12 gap-4 px-6 py-3 font-semibold text-xs text-gray-500 uppercase tracking-wider"><div className="col-span-4">{tab === 'pagos' ? 'Asesor / Pago' : 'Suscripción / Asesor'}</div><div className="col-span-3">{tab === 'pagos' ? 'Importe confirmado' : 'Periodo vigente'}</div><div className="col-span-2">Estado</div><div className="col-span-2">{tab === 'pagos' ? 'Confirmación' : 'Cupo'}</div><div className="col-span-1">Detalle</div></div>
        {tab === 'pagos' ? payments.data?.pages.flatMap(page => page.items).map(payment => <div key={payment.id} className={row}><div className="md:col-span-4 flex items-center gap-3"><div className="p-2.5 rounded-full bg-gray-50 dark:bg-inmo-darkbg text-gray-500"><CreditCard className="w-5 h-5" /></div><div className="min-w-0"><p className="font-bold truncate text-inmo-secondary dark:text-white">{payment.asesor}</p><p className="text-xs text-gray-500">Pago #{payment.id} · {payment.proveedor}</p></div></div><p className="md:col-span-3 font-montserrat font-bold text-inmo-accent">{payment.estado === 'CONFIRMADO' && payment.monto_confirmado !== null && payment.moneda === 'MXN' ? money(payment.monto_confirmado) : '—'}</p><span className={`md:col-span-2 text-xs font-bold ${payment.estado === 'CONFIRMADO' ? 'text-inmo-success' : 'text-gray-500'}`}>{payment.estado}</span><p className="md:col-span-2 text-xs text-gray-500">{date(payment.confirmado_at)}</p><div className="md:col-span-1"><IconButton variant="ghost" icon={<Eye className="w-5 h-5" />} aria-label={'Detalle del pago ' + payment.id} onClick={() => setSelected(payment)} /></div></div>) : subscriptions.data?.pages.flatMap(page => page.items).map(subscription => <div key={subscription.asesor_id} className={row}><p className="md:col-span-4 font-bold text-inmo-secondary dark:text-white">Suscripción #{subscription.id ?? '—'}<span className="block text-xs text-gray-500 font-normal">Asesor #{subscription.asesor_id}</span></p><p className="md:col-span-3 text-xs text-gray-500">{subscription.periodo ? `${date(subscription.periodo.inicio_at)} — ${date(subscription.periodo.fin_at)}` : 'Sin periodo vigente'}</p><span className="md:col-span-2 text-xs font-bold text-inmo-secondary dark:text-white">{subscription.estado}</span><p className="md:col-span-2 text-xs text-gray-500">{subscription.propiedades_en_cupo} / {subscription.limite_propiedades}<span className="block">Renovación: {subscription.renovacion_automatica ? 'activa' : 'desactivada'}</span></p><Link className="md:col-span-1 text-xs text-inmo-accent" to={'/admin/publicaciones?asesor=' + subscription.asesor_id}>Inventario</Link></div>)}
        {list.isPending && <p role="status" className="p-6 text-gray-500">Cargando registros…</p>}{!list.isPending && !list.isError && list.data?.pages.every(page => page.items.length === 0) && <p className="p-8 text-center text-gray-500">No hay registros en esta vista.</p>}
        {list.hasNextPage && <Button variant="secondary" isLoading={list.isFetchingNextPage} onClick={() => void list.fetchNextPage()}>Cargar más registros</Button>}
      </div>
    </div>
  </ModuleLayout>;
  const detail = selected && <div className="p-6 space-y-5 h-full overflow-y-auto font-inter"><h2 className="font-montserrat font-bold text-xl text-inmo-secondary dark:text-white">Pago #{selected.id}</h2><p>{selected.asesor}</p><dl className="space-y-4">{Object.entries({ Estado: selected.estado, Proveedor: selected.proveedor, Suscripción: selected.suscripcion_id, 'Importe confirmado': selected.monto_confirmado === null ? 'Sin confirmación' : `${selected.monto_confirmado} ${selected.moneda}`, Registro: date(selected.creado_at), Confirmación: date(selected.confirmado_at) }).map(([label, value]) => <div key={label}><dt className="text-xs text-gray-500 uppercase tracking-wider">{label}</dt><dd className="font-semibold text-inmo-secondary dark:text-white">{value}</dd></div>)}</dl></div>;
  return <SplitViewLayout mainContent={main} sideContent={detail} isOpen={!!selected} onClose={() => setSelected(null)} sideTitle="Detalle del pago" />;
}
