import { useState } from 'react';
import { useInfiniteQuery, useMutation } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { Eye, EyeOff, Archive, Building2 } from 'lucide-react';
import { ModuleLayout } from '../../templates/ModuleLayout';
import { SplitViewLayout } from '../../templates/SplitViewLayout';
import { SearchBar } from '../../molecules/SearchBar';
import { PeriodDropdown } from '../../molecules/PeriodDropdown';
import { ConfirmModal } from '../../molecules/ConfirmModal';
import { ConflictNotice } from '../../molecules/ConflictNotice';
import { Button } from '../../atoms/Button';
import { IconButton } from '../../atoms/IconButton';
import { Textarea } from '../../atoms/Textarea';
import { PropertyDetailContent } from '../../organisms/PropertyDetailContent';
import { getAdminProperties } from '../../../integrations/backend/administration.service';
import { useGetAdminProperty, useGetAdminPhotos, useGetAdminPhotoUrl, useModerateAdminProperty } from '../../../integrations/backend/hooks/useAdministration';
import { useGetCatalog } from '../../../integrations/backend/hooks/useProperties';
import { downloadCSV } from '../../../integrations/backend/operations.service';
import { operationError, isVersionConflict } from '../../../integrations/backend/versioning';
import type { PropiedadPrivada } from '../../../integrations/backend/types';

const states: Record<string, string | undefined> = { Todos: undefined, Borradores: 'REGISTRADA', Publicadas: 'PUBLICADA', Pausadas: 'PAUSADA', Archivadas: 'ARCHIVADA' };
const price = (amount: string) => Number(amount).toLocaleString('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 });
function Cover({ id, title }: { id: string; title: string }) {
  const photos = useGetAdminPhotos(id), photo = useGetAdminPhotoUrl(id, photos.data?.[0]?.id ?? '');
  return photo.data?.url ? <img src={photo.data.url} alt={title} className="w-16 h-16 rounded-xl object-cover shrink-0" /> : <div className="w-16 h-16 rounded-xl shrink-0 bg-gray-100 dark:bg-inmo-darkbg flex items-center justify-center text-gray-400" aria-label={photos.isError || photo.isError ? 'Fotografía no disponible' : photos.isPending || photo.isPending ? 'Cargando fotografía' : 'Sin fotografía'}><Building2 className="w-6 h-6" /></div>;
}
function StateBadge({ value }: { value: string }) { return <span className={`px-2 py-1 rounded-md text-[10px] font-bold uppercase ${value === 'PUBLICADA' ? 'bg-inmo-success/10 text-inmo-success' : value === 'PAUSADA' ? 'bg-inmo-warning/10 text-inmo-warning' : 'bg-gray-100 text-gray-500 dark:bg-inmo-darkbg'}`}>{value}</span>; }

export function AdminPublicationsView() {
  const [params, setParams] = useSearchParams(), selectedId = params.get('property') ?? '', advisor = params.get('asesor') ?? undefined;
  const [searchTerm, setSearchTerm] = useState(''), [statusFilter, setStatusFilter] = useState('Todos'), [reason, setReason] = useState(''), [conflict, setConflict] = useState(false), [action, setAction] = useState<'PAUSAR' | 'ARCHIVAR' | null>(null);
  const state = states[statusFilter];
  const list = useInfiniteQuery({ queryKey: ['admin', 'properties', searchTerm, state, advisor], queryFn: ({ pageParam }) => getAdminProperties({ limit: 20, cursor: pageParam, texto: searchTerm, estado: state, asesor_id: advisor }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor ?? undefined });
  const types = useGetCatalog('tipos'), detail = useGetAdminProperty(selectedId), moderate = useModerateAdminProperty();
  const properties = list.data?.pages.flatMap(page => page.items) ?? [], isOpen = !!selectedId;
  const exportCSV = useMutation({ mutationFn: () => downloadCSV('publicaciones', { texto: searchTerm, estado: state, asesor_id: advisor }) });
  const select = (id: string) => { setParams({ ...(advisor ? { asesor: advisor } : {}), property: id }); setReason(''); setConflict(false); moderate.reset(); };
  const handleClose = () => { setParams(advisor ? { asesor: advisor } : {}); setReason(''); setConflict(false); moderate.reset(); };
  const confirm = async () => { if (!detail.data || !action || !reason.trim() || conflict) throw new Error('Revisa la propiedad y escribe un motivo.'); try { await moderate.mutateAsync({ id: selectedId, accion: action, motivo: reason.trim(), etag: detail.data.etag }); setReason(''); } catch (error) { if (isVersionConflict(error)) { setConflict(true); setAction(null); } throw error; } };
  const actions = <div className="flex gap-3 items-center w-full"><PeriodDropdown selectedPeriod={statusFilter} onChange={setStatusFilter} options={Object.keys(states)} /><Button variant="secondary" isLoading={exportCSV.isPending} onClick={() => exportCSV.mutate()}>Exportar CSV</Button></div>;
  const pick = (property: PropiedadPrivada) => <div className="flex items-center gap-4"><Cover id={property.id} title={property.titulo} /><div className="flex flex-col min-w-0"><span className="font-bold text-inmo-secondary dark:text-white line-clamp-2 text-sm">{property.titulo}</span><span className="text-xs text-gray-500 truncate">{property.direccion}</span>{property.comparte_comision && <span className="text-xs text-inmo-accent font-bold">Comisión {property.porcentaje_comision}%</span>}</div></div>;
  const mainContent = <ModuleLayout title="Publicaciones" subtitle="Gestiona y modera el inventario global de la plataforma." isFullScreen noScroll showSearch={false} showFilters={false} controlsMaxWidthClass="md:hidden" actions={<div className="flex flex-col gap-3 w-full"><SearchBar placeholder="Buscar publicaciones..." value={searchTerm} onChange={setSearchTerm} size="slim" />{actions}</div>}>
    <div className="flex flex-col md:flex-row w-full h-full gap-6 font-inter pb-0 md:pb-6"><div className="flex flex-col h-full flex-1 min-w-0 gap-6">
      <div className="hidden md:flex gap-3 w-full items-center"><SearchBar placeholder="Buscar publicaciones..." value={searchTerm} onChange={setSearchTerm} size="slim" className="flex-1 md:flex-none md:w-[350px] min-w-0" /><div className="flex-1" />{actions}</div>
      {advisor && <Button variant="text" className="!justify-start" onClick={() => setParams({})}>Ver inventario de todos los asesores</Button>}
      {list.isError && <p role="alert">{operationError(list.error)}<button className="ml-3 text-inmo-accent" onClick={() => void list.refetch()}>Reintentar</button></p>}{exportCSV.isError && <p role="alert">{operationError(exportCSV.error)}</p>}
      <div className="bg-white dark:bg-inmo-darkcard rounded-card border border-gray-100 dark:border-inmo-darktertiary shadow-soft flex flex-col flex-1 min-h-0 animate-in fade-in slide-in-from-bottom-2">
        <div className="hidden md:block w-full flex-1 overflow-y-auto overflow-x-auto custom-scrollbar relative"><table className={`w-full text-left border-collapse h-fit ${isOpen ? 'min-w-full' : 'min-w-[900px]'}`}><thead className="sticky top-0 z-10 shadow-sm"><tr className="border-b border-gray-100 dark:border-inmo-darktertiary bg-gray-50/95 dark:bg-inmo-darkbg/95 backdrop-blur-md text-inmo-secondary dark:text-gray-300 font-montserrat text-sm"><th className="p-4 font-bold">Propiedad</th><th className={`p-4 font-bold ${isOpen ? 'hidden' : ''}`}>Tipo</th><th className="p-4 font-bold">Precio</th><th className="p-4 font-bold text-center">Estado</th>{['Recámaras', 'Baños', 'Área'].map(label => <th key={label} className={`p-4 font-bold text-center ${isOpen ? 'hidden' : ''}`}>{label}</th>)}<th className="p-4 font-bold text-right">Acciones</th></tr></thead><tbody className="font-inter">{properties.map(property => <tr key={property.id} className={`border-b border-gray-50 dark:border-inmo-darktertiary hover:bg-gray-50 dark:hover:bg-inmo-darkbg transition-colors ${selectedId === property.id ? 'bg-inmo-accent/5 dark:bg-inmo-accent/10' : ''}`}><td className="p-4"><button onClick={() => select(property.id)} className="text-left">{pick(property)}</button></td><td className={`p-4 ${isOpen ? 'hidden' : ''}`}>{types.data?.find(type => type.id === property.tipo_id)?.nombre ?? '…'}</td><td className="p-4"><span className="font-montserrat font-bold text-inmo-accent">{price(property.precio)}</span></td><td className="p-4 text-center"><StateBadge value={property.estado_publicacion} /></td>{[property.habitaciones, property.banos, property.superficie_construccion ?? property.superficie_terreno ?? '—'].map((value, index) => <td key={index} className={`p-4 text-center font-montserrat text-sm font-bold text-gray-600 dark:text-gray-300 ${isOpen ? 'hidden' : ''}`}>{value}{index === 2 && value !== '—' ? ' m²' : ''}</td>)}<td className="p-4 text-right"><IconButton variant="ghost" size="sm" icon={<Eye className="w-4 h-4" />} title="Revisar publicación" aria-label={'Revisar ' + property.titulo} onClick={() => select(property.id)} /></td></tr>)}{properties.length === 0 && <tr><td colSpan={8} className="p-8 text-center text-gray-500">{list.isPending ? 'Cargando publicaciones…' : 'No se encontraron propiedades.'}</td></tr>}</tbody></table></div>
        <div className="md:hidden flex flex-col font-inter flex-1 overflow-y-auto custom-scrollbar pb-6">{properties.map(property => <button key={property.id} onClick={() => select(property.id)} className="text-left p-4 border-b border-gray-100 dark:border-inmo-darktertiary">{pick(property)}<div className="mt-3 pt-3 border-t border-gray-100 dark:border-white/5 flex justify-between items-center"><span className="font-montserrat font-bold text-inmo-accent">{price(property.precio)}</span><StateBadge value={property.estado_publicacion} /></div></button>)}{properties.length === 0 && <p className="p-8 text-center text-gray-500">{list.isPending ? 'Cargando publicaciones…' : 'No se encontraron propiedades.'}</p>}</div>
      </div>{list.hasNextPage && <Button variant="secondary" isLoading={list.isFetchingNextPage} onClick={() => void list.fetchNextPage()}>Cargar más publicaciones</Button>}
    </div></div>
  </ModuleLayout>;
  const bottomBar = detail.data?.value.retirada_at ? <p className="p-4 text-sm text-gray-500">La publicación fue retirada definitivamente. Su historial se conserva.</p> : <div className="w-full p-4 space-y-3"><Textarea aria-label="Motivo de moderación" value={reason} onChange={event => setReason(event.target.value)} placeholder="Motivo obligatorio" maxLength={1000} /><div className="flex gap-3"><Button variant="secondary" disabled={!reason.trim() || conflict || moderate.isPending} icon={<EyeOff className="w-4 h-4" />} onClick={() => setAction('PAUSAR')}>Pausar</Button><Button variant="secondary" disabled={!reason.trim() || conflict || moderate.isPending} icon={<Archive className="w-4 h-4" />} onClick={() => setAction('ARCHIVAR')}>Archivar</Button></div>{conflict && <ConflictNotice current={<p>{detail.data?.value.estado_publicacion} · versión {detail.data?.value.version}</p>} onReview={async () => { const result = await detail.refetch(); if (result.isError) throw result.error; }} onAccept={() => { setConflict(false); moderate.reset(); }} />}{moderate.isError && !conflict && <p role="alert">{operationError(moderate.error)}</p>}{moderate.isSuccess && <p role="status">Moderación aplicada y auditada.</p>}</div>;
  const side = detail.isPending ? <p className="p-6">Cargando propiedad…</p> : detail.isError ? <p role="alert" className="p-6">{operationError(detail.error)}</p> : detail.data && <PropertyDetailContent property={detail.data.value} moderation bottomBar={bottomBar} />;
  return <><SplitViewLayout isOpen={isOpen} onClose={handleClose} sideTitle="Detalle de propiedad" sideContent={side} sidePanelWidthClass="md:w-[50%]" mainPanelWidthClass="md:w-[50%]" mainContent={mainContent} bottomSheetNoPadding bottomSheetHeightMode="fixed-85" /><ConfirmModal isOpen={!!action} onClose={() => setAction(null)} onConfirm={confirm} title={action === 'PAUSAR' ? 'Pausar publicación' : 'Archivar publicación'} message="La publicación dejará de aparecer públicamente; se conservarán sus conversaciones y su historial. El motivo quedará auditado." confirmText="Confirmar moderación" confirmVariant="warning" /></>;
}
