import { useState } from 'react';
import { useInfiniteQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { UserCheck, FileText, CheckCircle2, AlertCircle, Eye } from 'lucide-react';
import { ModuleLayout } from '../../templates/ModuleLayout';
import { SplitViewLayout } from '../../templates/SplitViewLayout';
import { Button } from '../../atoms/Button';
import { AdminUsersNavigation } from '../../molecules/AdminUsersNavigation';
import { IconButton } from '../../atoms/IconButton';
import { Textarea } from '../../atoms/Textarea';
import { ConfirmModal } from '../../molecules/ConfirmModal';
import { ConflictNotice } from '../../molecules/ConflictNotice';
import { getAdminApplications } from '../../../integrations/backend/advisors.service';
import { useGetAdminApplication, useDecideAdvisorApplication, useAdminDocumentUrl } from '../../../integrations/backend/hooks/useAdvisors';
import { useStatistics } from '../../../integrations/backend/hooks/useEngagement';
import { operationError, isVersionConflict } from '../../../integrations/backend/versioning';

const labels: Record<string, string> = { IDENTIFICACION_OFICIAL: 'Identificación oficial', CONSTANCIA_SITUACION_FISCAL: 'Constancia de situación fiscal', CONSTANCIA_ACTIVIDAD_INMOBILIARIA: 'Constancia de actividad inmobiliaria', LICENCIA_INMOBILIARIA: 'Licencia inmobiliaria (opcional)' };
const date = (value?: string | null) => value ? new Date(value).toLocaleString('es-MX', { timeZone: 'America/Mexico_City' }) : '—';
function Badge({ state }: { state: string }) { return <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase ${state === 'APROBADA' ? 'bg-inmo-success/10 text-inmo-success' : state === 'RECHAZADA' ? 'bg-inmo-danger/10 text-inmo-danger' : 'bg-inmo-warning/10 text-inmo-warning'}`}>{state}</span>; }
export function AdminApplicationsView() {
  const [params, setParams] = useSearchParams(), id = params.get('solicitud') ?? '';
  const [reason, setReason] = useState(''), [action, setAction] = useState<'APROBAR' | 'RECHAZAR' | null>(null), [conflict, setConflict] = useState(false), [document, setDocument] = useState<{ id: string; url: string; expires_at: string } | null>(null);
  const list = useInfiniteQuery({ queryKey: ['admin', 'applications', 'all'], queryFn: ({ pageParam }) => getAdminApplications({ limit: 20, cursor: pageParam }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor ?? undefined });
  const statistics = useStatistics(true, 30), detail = useGetAdminApplication(id), decide = useDecideAdvisorApplication(), download = useAdminDocumentUrl();
  const items = list.data?.pages.flatMap(page => page.items) ?? [], current = detail.data?.value, required = current?.tipos_requeridos ?? ['IDENTIFICACION_OFICIAL', 'CONSTANCIA_ACTIVIDAD_INMOBILIARIA'];
  const complete = !!current && required.every(type => current.documentos.some(document => document.tipo === type));
  const select = (id: string) => { setParams(id ? { solicitud: id } : {}); setReason(''); setAction(null); setConflict(false); setDocument(null); decide.reset(); download.reset(); };
  const confirm = async () => { if (!detail.data || !action || conflict || (action === 'APROBAR' && !complete) || (action === 'RECHAZAR' && !reason.trim())) throw new Error('Revisa el expediente antes de confirmar.'); try { await decide.mutateAsync({ id, decision: action, motivo: reason.trim() || null, etag: detail.data.etag }); setReason(''); } catch (error) { if (isVersionConflict(error)) { setConflict(true); setAction(null); } throw error; } };
  const main = <ModuleLayout title="Autorizaciones de asesores" subtitle="Verifica los documentos privados y decide con evidencia." isFullScreen noScroll showSearch={false} showFilters={false}>
    <div className="flex flex-col h-full min-h-0 gap-6 font-inter pb-24"><div className="flex flex-col md:flex-row gap-4 shrink-0"><div className="flex-1"><AdminUsersNavigation /></div><div className="bg-white dark:bg-inmo-darkcard p-3 lg:p-4 rounded-card border border-gray-100 dark:border-inmo-darktertiary shadow-soft flex gap-3 items-center"><UserCheck className="text-inmo-accent w-6 h-6" /><div><p className="font-montserrat font-black text-2xl text-inmo-accent">{statistics.data?.autorizaciones_pendientes ?? '—'}</p><p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Pendientes de revisión</p></div></div></div>
      {(list.isError || statistics.isError) && <p role="alert">{operationError(list.error ?? statistics.error)} <button className="text-inmo-accent" onClick={() => { void list.refetch(); void statistics.refetch(); }}>Reintentar</button></p>}
      <div className="bg-white dark:bg-inmo-darkcard rounded-card border border-gray-100 dark:border-inmo-darktertiary shadow-soft flex-1 min-h-0 overflow-y-auto custom-scrollbar"><table className="hidden md:table w-full text-left border-collapse"><thead className="sticky top-0 z-10 bg-gray-50/95 dark:bg-inmo-darkbg/95 backdrop-blur-md font-montserrat text-sm shadow-sm"><tr>{['Asesor / Solicitud', 'Fecha', 'Documentos', 'Estado', 'Acción'].map(label => <th key={label} className="p-4 font-bold text-inmo-secondary dark:text-white">{label}</th>)}</tr></thead><tbody>{items.map(item => <tr key={item.id} className={`border-b border-gray-50 dark:border-inmo-darktertiary hover:bg-gray-50 dark:hover:bg-inmo-darkbg ${item.id === id ? 'bg-inmo-accent/5' : ''}`}><td className="p-4"><button onClick={() => select(item.id)} className="text-left"><p className="font-bold text-inmo-secondary dark:text-white">{item.nombre_comercial || 'Asesor #' + item.asesor_id}</p><p className="text-xs text-gray-500">Solicitud #{item.id}</p></button></td><td className="p-4 text-sm text-gray-500">{date(item.enviada_at)}</td><td className="p-4 text-sm text-gray-500">{item.documentos.length} recibidos · {item.requisitos_version}</td><td className="p-4"><Badge state={item.estado} /></td><td className="p-4"><IconButton variant="ghost" icon={<Eye className="w-5 h-5" />} aria-label={'Revisar solicitud ' + item.id} onClick={() => select(item.id)} /></td></tr>)}</tbody></table>
        <div className="md:hidden">{items.map(item => <button key={item.id} onClick={() => select(item.id)} className="w-full p-4 border-b border-gray-100 dark:border-inmo-darktertiary text-left space-y-3"><div className="flex justify-between gap-2"><span className="font-bold text-inmo-secondary dark:text-white">{item.nombre_comercial || 'Asesor #' + item.asesor_id}</span><Badge state={item.estado} /></div><p className="text-xs text-gray-500">Solicitud #{item.id} · {date(item.enviada_at)} · {item.documentos.length} documentos</p></button>)}</div>
        {!items.length && <p className="p-8 text-center text-gray-500">{list.isPending ? 'Cargando solicitudes…' : list.isError ? 'La consulta no está disponible.' : 'No hay solicitudes.'}</p>}
      </div>{list.hasNextPage && <Button variant="secondary" isLoading={list.isFetchingNextPage} onClick={() => void list.fetchNextPage()}>Cargar más solicitudes</Button>}
    </div>
  </ModuleLayout>;
  const side = <div className="h-full overflow-y-auto overscroll-contain custom-scrollbar p-6 pb-12 space-y-5 font-inter">{detail.isPending ? <p role="status">Cargando expediente…</p> : detail.isError ? <p role="alert">{operationError(detail.error)}</p> : current && <><div className="flex items-center gap-3"><div className="rounded-full bg-inmo-accent/10 p-4 text-inmo-accent"><UserCheck className="w-7 h-7" /></div><div><h2 className="font-montserrat font-bold text-xl text-inmo-secondary dark:text-white">{current.nombre_comercial || 'Asesor #' + current.asesor_id}</h2><p className="text-xs text-gray-500 mt-1">Solicitud #{current.id} · {date(current.enviada_at)}</p></div></div><Badge state={current.estado} />
      <section className="bg-gray-50 dark:bg-inmo-darkbg p-4 rounded-2xl space-y-3"><h3 className="font-montserrat font-bold">Requisitos del expediente · {current.requisitos_version}</h3>{required.map(type => { const present = current.documentos.some(document => document.tipo === type); return <p key={type} className="flex gap-2 text-sm items-center">{present ? <CheckCircle2 className="w-4 h-4 text-inmo-success" /> : <AlertCircle className="w-4 h-4 text-inmo-warning" />}<span>{labels[type] ?? type} · {present ? 'Recibido' : 'Pendiente'}</span></p>; })}<p className="text-xs text-gray-500">La licencia es opcional. Los expedientes anteriores conservan sus requisitos originales.</p></section>
      <section className="space-y-3"><h3 className="font-montserrat font-bold text-lg">Documentos privados</h3>{current.documentos.length ? current.documentos.map(item => <article key={item.id} className="p-4 bg-white dark:bg-inmo-darkcard rounded-2xl border border-gray-100 dark:border-inmo-darktertiary space-y-2"><div className="flex gap-2 items-center"><FileText className="w-5 h-5 text-inmo-accent shrink-0" /><p className="font-bold text-sm break-words">{labels[item.tipo ?? ''] ?? 'Documento'}<span className="block text-xs text-gray-500 font-normal">{item.nombre} · {(item.tamano_bytes / 1024).toFixed(0)} KB · {item.estado}</span></p></div><Button variant="text" isLoading={download.isPending && download.variables === item.id} onClick={async () => { setDocument(null); try { setDocument({ id: item.id, ...(await download.mutateAsync(item.id)) }); } catch { /* error below */ } }}>Solicitar enlace privado</Button>{document?.id === item.id && <div className="space-y-1"><a className="text-inmo-accent underline text-sm" href={document.url} target="_blank" rel="noopener noreferrer">Abrir documento</a><p className="text-xs text-gray-500">Enlace válido hasta {date(document.expires_at)}</p></div>}</article>) : <p className="text-sm text-gray-500">Todavía no se han recibido documentos.</p>}{download.isError && <p role="alert">{operationError(download.error)}</p>}</section>
      {current.motivo && <div className="rounded-2xl p-4 bg-gray-50 dark:bg-inmo-darkbg"><p className="font-bold text-sm">Motivo de decisión</p><p className="text-sm whitespace-pre-wrap mt-2">{current.motivo}</p><p className="text-xs text-gray-500 mt-2">{date(current.resuelta_at)}</p></div>}
      {current.estado === 'PENDIENTE' && <section className="space-y-4"><Textarea aria-label="Motivo de decisión" placeholder="Motivo; obligatorio para rechazar" value={reason} onChange={event => setReason(event.target.value)} maxLength={1000} /><div className="flex gap-3"><Button disabled={!complete || conflict || decide.isPending} onClick={() => setAction('APROBAR')}>Aprobar</Button><Button variant="danger" disabled={!reason.trim() || conflict || decide.isPending} onClick={() => setAction('RECHAZAR')}>Rechazar</Button></div>{!complete && <p className="text-xs text-gray-500">La aprobación requiere los documentos obligatorios.</p>}</section>}
      {conflict && <ConflictNotice current={<p>Estado vigente: {current.estado} · versión {current.version}</p>} onReview={async () => { const result = await detail.refetch(); if (result.isError) throw result.error; }} onAccept={() => { setConflict(false); decide.reset(); }} />}{decide.isError && !conflict && <p role="alert">{operationError(decide.error)}</p>}{decide.isSuccess && <p role="status" className="text-inmo-success text-sm">Decisión aplicada y auditada.</p>}
    </>}</div>;
  return <><SplitViewLayout mainContent={main} sideContent={side} isOpen={!!id} onClose={() => select('')} sideTitle="Expediente profesional" /><ConfirmModal isOpen={!!action} onClose={() => setAction(null)} onConfirm={confirm} title={action === 'APROBAR' ? 'Autorizar asesor' : 'Rechazar solicitud'} message="La decisión se aplicará al expediente vigente y quedará auditada. Revisa los documentos y el motivo antes de confirmar." confirmText="Confirmar decisión" confirmVariant={action === 'RECHAZAR' ? 'danger' : 'accent'} /></>;
}
