const fs = require('fs');
const file = 'src/components/views/admin/AdminPublicationsView.tsx';
let content = fs.readFileSync(file, 'utf8');

// Add Mail import
if (!content.includes('Mail,')) {
    content = content.replace('MessageSquare,', 'MessageSquare,\n  Mail,');
}

// Replace header
content = content.replace(/>Rendimiento<\/th>/g, '>Contacto</th>');

// Replace td content for Rendimiento
// The original td is:
/*
                          <td className={`p-4 align-middle text-center ${isOpen ? 'hidden' : ''}`}>
                            <div className="flex items-center justify-center gap-3 text-sm text-gray-600 dark:text-gray-300">
                              <span className="flex items-center gap-1 font-montserrat"><Eye className="w-4 h-4 text-gray-400" /> {prop.views}</span>
                              <span className="flex items-center gap-1 font-montserrat"><MessageSquare className="w-4 h-4 text-gray-400" /> {prop.messages}</span>
                            </div>
                          </td>
*/
const oldTd = `<td className={\`p-4 align-middle text-center \${isOpen ? 'hidden' : ''}\`}>
                            <div className="flex items-center justify-center gap-3 text-sm text-gray-600 dark:text-gray-300">
                              <span className="flex items-center gap-1 font-montserrat"><Eye className="w-4 h-4 text-gray-400" /> {prop.views}</span>
                              <span className="flex items-center gap-1 font-montserrat"><MessageSquare className="w-4 h-4 text-gray-400" /> {prop.messages}</span>
                            </div>
                          </td>`;

const newTd = `<td className={\`p-4 align-middle text-center \${isOpen ? 'hidden' : ''}\`}>
                            <div className="flex items-center justify-center gap-2">
                              <IconButton variant="ghost" size="sm" icon={<Mail className="w-4 h-4 text-inmo-secondary" />} title="Enviar Correo" onClick={(e) => { e.stopPropagation(); }} />
                              <IconButton variant="ghost" size="sm" icon={<MessageSquare className="w-4 h-4 text-inmo-secondary" />} title="Enviar Mensaje" onClick={(e) => { e.stopPropagation(); }} />
                            </div>
                          </td>`;

content = content.replace(oldTd, newTd);


// Remove Pausar action from ActionMenu (desktop and mobile)
// Note: Due to weird characters like 'Activar PublicaciA3n' or 'Activar Publicaci??n' generated by previous finds, I will just use regex to remove that entire line.
content = content.replace(/\{ label: prop\.status === 'Activa' \? 'Pausar' : 'Activar[\s\S]*?\},/g, '');

// Remove Pausar action from Grid IconButtons
// <IconButton variant="ghost" size="sm" icon={prop.status === 'Activa' ? <EyeOff className="w-4 h-4" /> : <Power className="w-4 h-4" />} title={prop.status === 'Activa' ? 'Pausar' : 'Activar'} onClick={(e) => { e.stopPropagation(); requestToggleStatus(prop); }} />
content = content.replace(/<IconButton variant="ghost" size="sm" icon=\{prop\.status === 'Activa' \? <EyeOff[\s\S]*?requestToggleStatus[\s\S]*?\/>/g, '');


fs.writeFileSync(file, content);
console.log('Fixed Contacto and Duplicate Actions');
