import { Link } from 'react-router-dom';
import { ComposedChart, Area, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Activity, Building2, DollarSign } from 'lucide-react';
import type { Estadisticas } from '../../integrations/backend/engagement.service';

export const periodDays: Record<string, number> = { Semana: 7, Mes: 30, '1 Mes': 30, '3 Meses': 90, '6 Meses': 180, Año: 365 };
export type ChartViewMode = 'dias' | 'semanas' | 'meses';
export function measuredChart(data: Estadisticas | undefined, mode: ChartViewMode, metric: 'visitas' | 'contactos' = 'visitas') {
  if (!data) return [];
  const begin = new Date(new Date(data.desde).toLocaleDateString('sv-SE', { timeZone: 'America/Mexico_City' }) + 'T12:00:00Z');
  const end = new Date(new Date(data.hasta).toLocaleDateString('sv-SE', { timeZone: 'America/Mexico_City' }) + 'T12:00:00Z');
  const measured = new Map(metric === 'visitas' ? data.serie_visitas.map(item => [item.dia, item.visitas] as const) : data.serie_contactos.map(item => [item.dia, item.contactos] as const)), grouped = new Map<string, number>();
  for (let day = new Date(begin); day <= end; day = new Date(day.getTime() + 86_400_000)) {
    let key = day.toISOString().slice(0, 10);
    if (mode === 'meses') key = key.slice(0, 7);
    else if (mode === 'semanas') { const monday = new Date(day); monday.setUTCDate(day.getUTCDate() - (day.getUTCDay() + 6) % 7); key = monday.toISOString().slice(0, 10); }
    grouped.set(key, (grouped.get(key) ?? 0) + (measured.get(day.toISOString().slice(0, 10)) ?? 0));
  }
  return [...grouped].map(([label, views]) => ({ label, views }));
}
export function TrafficChart({ data, mode = 'dias' }: { data?: Estadisticas; mode?: ChartViewMode }) {
  return <div className="flex flex-col min-h-0 h-full gap-2"><div className="flex-1 min-h-[200px] w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={measuredChart(data, mode)} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}><defs><linearGradient id="real-traffic-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#FA003F" stopOpacity={0.2} /><stop offset="95%" stopColor="#FA003F" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="currentColor" className="text-gray-200 dark:text-white/5" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#9ca3af' }} minTickGap={30} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#9ca3af' }} /><Tooltip content={({ active, payload, label }) => active && payload?.length ? <div className="bg-white dark:bg-inmo-darkcard border border-gray-100 dark:border-white/10 rounded-xl p-3 shadow-soft font-inter"><p className="font-montserrat font-bold mb-1">{label}</p><p className="text-inmo-accent font-bold text-xs">Visitas: {payload[0].value}</p></div> : null} /><Area type="monotone" dataKey="views" stroke="none" fill="url(#real-traffic-gradient)" activeDot={false} /><Line type="monotone" dataKey="views" stroke="#FA003F" strokeWidth={3} dot={false} activeDot={{ r: 6 }} /></ComposedChart></ResponsiveContainer></div><p className="text-[10px] text-gray-400">{data ? `${new Date(data.desde).toLocaleDateString('es-MX')} – ${new Date(data.hasta).toLocaleDateString('es-MX')} · CDMX. Instrumentación desde ${new Date(data.instrumentacion_desde).toLocaleDateString('es-MX')}.` : 'Cargando periodo…'}</p></div>;
}
export function PortfolioStatistics({ data }: { data?: Estadisticas }) {
  const total = Object.values(data?.estados ?? {}).reduce((sum, count) => sum + count, 0);
  return <div className="flex flex-col gap-3"><div className="bg-white dark:bg-inmo-darkcard rounded-card p-5 shadow-soft border border-gray-100 dark:border-inmo-darktertiary"><div className="flex items-center gap-2 mb-4"><DollarSign className="w-4 h-4 text-gray-400" /><p className="font-inter text-xs font-bold text-gray-400 uppercase tracking-wider">Valor del portafolio</p></div><span className="font-montserrat font-black text-3xl md:text-4xl">{data ? Number(data.valor_portafolio_mxn).toLocaleString('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 }) : '—'}</span><p className="text-[11px] text-gray-400 mt-1">Precio anunciado de propiedades sin retirada definitiva.</p></div>
    <div className="bg-white dark:bg-inmo-darkcard rounded-card p-5 shadow-soft border border-gray-100 dark:border-inmo-darktertiary"><p className="font-inter text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">Estado de propiedades</p><div className="w-full h-3 rounded-full bg-gray-100 dark:bg-gray-800 overflow-hidden flex mb-3">{Object.entries(data?.estados ?? {}).map(([state, count], index) => <div key={state} title={`${state}: ${count}`} className={['bg-inmo-success', 'bg-inmo-warning', 'bg-gray-300', 'bg-inmo-accent'][index % 4]} style={{ width: total ? `${count / total * 100}%` : '0%' }} />)}</div>{Object.entries(data?.estados ?? {}).map(([state, count]) => <div key={state} className="flex justify-between py-1"><span className="text-sm">{state}</span><span className="font-montserrat font-bold">{count}</span></div>)}</div>
    <div className="grid grid-cols-2 gap-3">{data?.tipos.map(item => <div key={item.id} className="bg-white dark:bg-inmo-darkcard rounded-card p-3 shadow-soft border border-gray-100 dark:border-inmo-darktertiary text-center"><div className="flex items-center justify-center gap-2"><span className="text-xs text-gray-500">{item.nombre}</span><Building2 className="w-3.5 h-3.5 text-gray-400" /></div><span className="font-montserrat font-black text-2xl md:text-3xl block my-2">{item.propiedades}</span><p className="text-[10px] text-gray-500">{Number(item.valor_mxn).toLocaleString('es-MX', { style: 'currency', currency: 'MXN' })}</p></div>)}</div><Link to="/asesor/propiedades" className="text-inmo-accent font-bold text-sm text-center py-4">Gestionar mi inventario</Link></div>;
}
export function PropertyRanking({ data }: { data?: Estadisticas }) {
  return <div className="space-y-4"><p className="font-inter text-xs text-gray-500">Visitas del periodo; contactos como desempate. Cada contacto corresponde al primer mensaje de un cliente por inmueble.</p>{data?.ranking.length === 0 && <p>No hay inmuebles en el inventario.</p>}{data?.ranking.map((item, index) => <Link key={item.id} to={'/asesor/propiedades?property=' + item.id} className="block bg-white dark:bg-inmo-darkcard rounded-card p-5 shadow-soft border border-gray-100 dark:border-inmo-darktertiary"><p className="font-montserrat font-bold">#{index + 1} · {item.titulo}</p><p className="text-sm text-gray-500 mt-3">{item.visitas} visitas · {item.contactos} contactos · {item.estado}</p></Link>)}</div>;
}
export function TrafficHeading() { return <div className="flex items-center gap-1.5"><Activity className="w-4 h-4 text-gray-400" /><h4 className="font-montserrat font-bold text-sm">Tráfico</h4></div>; }
